### ISSUE TITLE
It crashes when is inside angular routing

### ISSUE THREAD

**Issue by llorenspujol** [alexcastillo/ng2-notifications#14]
I know that the notificacions have to be on the top of the routing in order to be global, but this is not my case. I have the notifications in a component that is in the middle of the routing tree. It goes perfect when I am in this component, but when I go to a same level component or parent, it crashes.

I've made a plunkr showing this error, I've take the angular2 example last routing and I have put the notifications (you could find it in the CrisisCenterComponent). You will see that the application works perfectly until we change the component.

Plunkr: http://plnkr.co/edit/p6oiZ87ySc7rVn1GqUu7?p=preview

Thank you in advice! nice work.

**Comment by ghost** [comment]
@llorenspujol, I have the same situation as you (a component in the middle of the routing tree, I use modules however) and I get the same issue : 
TypeError: Notification.close is not a function
and my app crashes.
Did you solve your problem since your initial post ?
Thank you.

**Comment by yceruto** [comment]
Same problem here (Google Chrome), any solution for that??

**Comment by yceruto** [comment]
> TypeError: Notification.close is not a function

https://github.com/alexcastillo/ng2-notifications/blob/master/src/app/components/notification.component.ts#L99
```
Notification.close();
```
The current implementation look wrong, probably this should be referred to one notification instance, see example in https://developer.mozilla.org/en-US/docs/Web/API/Notification/close
