### ISSUE TITLE
Using literals as inputs

### ISSUE THREAD

**Issue by Foxandxss** [alexcastillo/ng2-notifications#2]
Been seeing your issue at our preboot repo and came here to peek.

I see your doc stuff like:

```
[title]="'ng2-notifications'"
```

And:

```
[sound]="'./url/to/custom/sound.mp3'"
```

Is there any good reason? You can do:

```
title="ng2-notifications"
sounds="./foo/bar.mp3"
```

Use [] for bindings and remove it for literal strings.

**Comment by alexcastillo** [comment]
Hi @Foxandxss,

Thanks for the feedback!
I've updated the documentation to reflect this.

https://github.com/alexcastillo/ng2-notifications/blob/master/README.md

Alex
